/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_dsstne_knn_KNearestNeighborsCuda */

#ifndef _Included_com_amazon_dsstne_knn_KNearestNeighborsCuda
#define _Included_com_amazon_dsstne_knn_KNearestNeighborsCuda
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_dsstne_knn_KNearestNeighborsCuda_NULLPTR
#define com_amazon_dsstne_knn_KNearestNeighborsCuda_NULLPTR 0LL
#undef com_amazon_dsstne_knn_KNearestNeighborsCuda_DEFAULT_KEYVAL_DELIM
#define com_amazon_dsstne_knn_KNearestNeighborsCuda_DEFAULT_KEYVAL_DELIM 9L
#undef com_amazon_dsstne_knn_KNearestNeighborsCuda_DEFAULT_VEC_DELIM
#define com_amazon_dsstne_knn_KNearestNeighborsCuda_DEFAULT_VEC_DELIM 32L
/*
 * Class:     com_amazon_dsstne_knn_KNearestNeighborsCuda
 * Method:    initialize
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_amazon_dsstne_knn_KNearestNeighborsCuda_initialize
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_amazon_dsstne_knn_KNearestNeighborsCuda
 * Method:    load
 * Signature: ([Ljava/lang/String;[ICCJ)V
 */
JNIEXPORT void JNICALL Java_com_amazon_dsstne_knn_KNearestNeighborsCuda_load
  (JNIEnv *, jclass, jobjectArray, jintArray, jchar, jchar, jlong);

/*
 * Class:     com_amazon_dsstne_knn_KNearestNeighborsCuda
 * Method:    shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_amazon_dsstne_knn_KNearestNeighborsCuda_shutdown
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_amazon_dsstne_knn_KNearestNeighborsCuda
 * Method:    findKnn
 * Signature: (I[FII[F[Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_amazon_dsstne_knn_KNearestNeighborsCuda_findKnn__I_3FII_3F_3Ljava_lang_String_2J
  (JNIEnv *, jclass, jint, jfloatArray, jint, jint, jfloatArray, jobjectArray, jlong);

/*
 * Class:     com_amazon_dsstne_knn_KNearestNeighborsCuda
 * Method:    findKnn
 * Signature: (I[FIIJ)Lcom/amazon/dsstne/knn/KnnResult;
 */
JNIEXPORT jobject JNICALL Java_com_amazon_dsstne_knn_KNearestNeighborsCuda_findKnn__I_3FIIJ
  (JNIEnv *, jclass, jint, jfloatArray, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
